#[cfg(feature = "gui")]
pub mod actions;
pub mod client;
pub mod config;
#[cfg(feature = "gui")]
pub mod desktop;
#[cfg(feature = "gui")]
pub mod file_ops;
pub mod index;
pub mod query;
pub mod runtime;
pub mod service;
#[cfg(feature = "gui")]
pub mod settings_ui;
pub mod shortcuts;
pub mod store;
pub mod table;
#[cfg(feature = "gui")]
pub mod ui;
pub mod watch;
